### ISSUE TITLE
Handle updated datapoint on Sync API

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/siwins#11]
- Updated Registration datapoint coming from flow, should be only updated the datapoint and answers, no datapoint going to the history table
- Updated Monitoring datapoint coming from flow, should only update the datapoint and answers, no datapoint going to the history table
- New Monitoring datapoint coming from flow, the new monitoring data should be current answers and the previous answers will be moved to the history table
---
**REFACTOR**
- [x] use `formsInstanceId` as table data-id instead of using auto-increment (datapoint seeder file)
  - need to save all datapoint for monitoring data
- [x] use this updated id to detect updated/new datapoint coming from flow sync (data_sync file)
  - check the answer and history table for updated data

**Comment by joycarpediem** [comment]
@ifirmawan , can you please look at this and if all good then merge and move to "Ready for testing "

**Comment by ifirmawan** [comment]
sure @joycarpediem , I'm working on it

**Comment by joycarpediem** [comment]
@navins94 , can you please test this 

All actions happen in flow and the effect should be visible in siwins after the sync
Test cases:
1. add a new data point in flow .Registration  Run Sync
 Expected : Only one data point is fetched and shown in the UI
 2. add a monitoring submission . Run sync
 Expected : Only the monitoring submission is fetched
3. Add second monitoring submission (1)
Expected : Only the second monitoring submission is fetched . The first monitoring submission is moved to history
4. Update the response to a question in the registration submission 
Expected : Only the answer to that submission is fetched and updated
5. Do test 4 for monitoring submission (1) that was added in test 2
Expected : The history data is updated
6. Do test 5 but for monitoring submission (2)
Expected : The "current" answer table is updated
7. Update a question text in the registration form
Expected : The question text is updated in the sync
8. Delete monitoring submission (1)
Expected : Submission is removed from the history  table
9. Do test 8 for the registration data
Expected : The registration data point as well as monitoring submission (2) is removed

**Comment by navins94** [comment]
Hi @joycarpediem what should be the new data point. Should we install app from Akvo flow or any other way

**Comment by ifirmawan** [comment]
run sync
```
docker-compose exec backend python -m seeder.data_sync
```

**Comment by navins94** [comment]
@joycarpediem I tested above points. Except delete everything is working fine

CC: @wayangalihpratama
